# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "sinatra"
gem 'sinatra-reloader', '~> 1.0'
gem "rubocop"
gem 'erb_lint', require: false